Repository phpro/soap-client, pull requests merged in 2018-10, with the labels that each got.

#194 Added ConstructorAssemblerOptions
  docs/code-generation/assemblers.md
  src/Phpro/SoapClient/CodeGenerator/Assembler/ConstructorAssembler.php
  src/Phpro/SoapClient/CodeGenerator/Assembler/ConstructorAssemblerOptions.php
  src/Phpro/SoapClient/CodeGenerator/ConfigGenerator.php
  test/PhproTest/SoapClient/Unit/CodeGenerator/Assembler/ConstructorAssemblerTest.php
  test/PhproTest/SoapClient/Unit/CodeGenerator/ConfigGeneratorTest.php
Labels: new feature

#196 Normalization fixes
  spec/Phpro/SoapClient/CodeGenerator/Model/ClientMethodSpec.php
  spec/Phpro/SoapClient/CodeGenerator/Util/NormalizerSpec.php
  src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php
  src/Phpro/SoapClient/CodeGenerator/Model/ClientMethod.php
  src/Phpro/SoapClient/CodeGenerator/Model/Property.php
  src/Phpro/SoapClient/CodeGenerator/Parser/FunctionStringParser.php
  src/Phpro/SoapClient/CodeGenerator/Util/Normalizer.php
  test/PhproTest/SoapClient/Unit/CodeGenerator/Assembler/ClientMethodAssemblerTest.php
  test/PhproTest/SoapClient/Unit/CodeGenerator/Assembler/FluentSetterAssemblerTest.php
  test/PhproTest/SoapClient/Unit/CodeGenerator/Assembler/GetterAssemblerTest.php
Labels: enhancement

#189 Additional functional tests
  README.md
  docs/known-issues/ext-soap.md
  test/PhproTest/SoapClient/Functional/AbstractSoapTestCase.php
  test/PhproTest/SoapClient/Functional/Encoding/Base64BinaryTest.php
  test/PhproTest/SoapClient/Functional/Encoding/DuplicateTypenamesTest.php
  test/PhproTest/SoapClient/Functional/Encoding/EnumTest.php
  test/fixtures/wsdl/functional/duplicate-typenames.wsdl
  test/fixtures/wsdl/functional/enum.wsdl
Labels: improve documentation
