Repository phpro/soap-client, pull requests merged in 2021-12, with the labels that each got.

#401 work arround differences between guzzle-psr7 and nyholm-psr7 requests
  src/Phpro/SoapClient/Xml/Xml.php
  test/PhproTest/SoapClient/Unit/Xml/SoapXmlTest.php
Labels: bug

#406 Don't import known types
  src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php
  test/PhproTest/SoapClient/Unit/CodeGenerator/Assembler/ClientMethodAssemblerTest.php
Labels: enhancement

#407 Fixes rules.md documentation
  docs/code-generation/rules.md
Labels: improve documentation
